### ISSUE TITLE
Better handling if Server API has problems

### ISSUE THREAD

**Issue by MTRNord** [SocialNetworkNews/SocialNetworkNews-Web#1]
https://sentry.io/nordgedanken/socialnetworksnews/issues/473719498/

```
Error: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":500,"statusText":"Internal Server Error","url":"https://freifunknews.nordgedanken.blog/api/paper/undefined/yesterday","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://freifunknews.nordgedanken.blog/api/paper/undefined/yesterday: 500 Internal Server Error","error":"open data/tweets_2018_02_25.csv: no such file or directory\n"}
  at cDNt/ms</t.prototype.getYesterday/< (/main.5caa3077883774cf1996.bundle.js:1:445424)
  at E9/g/l</e.prototype.__tryOrUnsub (/main.5caa3077883774cf1996.bundle.js:1:7263)
  at E9/g/l</e.prototype.error (/main.5caa3077883774cf1996.bundle.js:1:6747)
  at E9/g/u</e.prototype._error (/main.5caa3077883774cf1996.bundle.js:1:5660)
  at E9/g/u</e.prototype.error (/main.5caa3077883774cf1996.bundle.js:1:5366)
...
(16 additional frame(s) were not displayed)
```

**Comment by MTRNord** [comment]
18ffb5b4db22c97daac4669820f111028bdf4308  <-- this propably fixes it partialy
